class_name Groups

const CONNECTABLE_BODIES = "connectable_bodies"
const CONNECTABLE_STATE = "connectable_state"
const PREVIEW_CONNECTIONS = "preview_connections"
const GREEN_GOOS = "green_goos"
const RED_GOOS = "red_goos"
const PURPLE_CONNECTABLE_BODIES = "purple_connectable_bodies"
const PURPLE_CONNECTABLES = "purple_connectables"
const PURPLE_GOOS = "purple_goos"
const LEVELS = "levels"
const CONNECTIONS = "connections"
const PURPLE_CONNECTIONS = "purple_connections"
const SOLID_CONNECTIONS = "solid_connections"
const RED_CONNECTIONS = "red_connections"
const PLAYERS = "players"
const BULLET_REFLECTORS = "bullet_reflectors"
const CONNECTION_LINES = "connection_lines"
const PISTO_GRABBABLE_AREAS = "pisto_grabbable_areas"
const BONUS = "bonus"
const FOCUSABLES = "focusables"
