class_name Groups

const GOO_BODIES = "goo_bodies"
const CONNECTABLE_GOO_BODIES = "connectable_goo_bodies"
const CONNECTED_GOO_BODIES = "connected_goo_bodies"
const CONNECTABLE_STATE = "connectable_state"
const PREVIEW_CONNECTIONS = "preview_connections"
const GREEN_GOOS = "green_goos"
const RED_GOOS = "red_goos"
const PURPLE_GOO_BODIES = "purple_goo_bodies"
const PURPLE_GOOS = "purple_goos"
const LEVELS = "levels"
const CONNECTIONS = "connections"
const PURPLE_CONNECTIONS = "purple_connections"
const SOLID_CONNECTIONS = "solid_connections"
const RED_CONNECTIONS = "red_connections"
